// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: grpcx/proto/reddb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpcx_proto_reddb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpcx_proto_reddb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpcx_proto_reddb_proto_rawDescGZIP(), []int{0}
}

type HealthReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Healthy         bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	State           string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	CheckedAtUnixMs uint64                 `protobuf:"varint,3,opt,name=checked_at_unix_ms,json=checkedAtUnixMs,proto3" json:"checked_at_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthReply) Reset() {
	*x = HealthReply{}
	mi := &file_grpcx_proto_reddb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReply) ProtoMessage() {}

func (x *HealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpcx_proto_reddb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReply.ProtoReflect.Descriptor instead.
func (*HealthReply) Descriptor() ([]byte, []int) {
	return file_grpcx_proto_reddb_proto_rawDescGZIP(), []int{1}
}

func (x *HealthReply) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *HealthReply) GetCheckedAtUnixMs() uint64 {
	if x != nil {
		return x.CheckedAtUnixMs
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	EntityTypes   []string               `protobuf:"bytes,2,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	Capabilities  []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Params        []*QueryValue          `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_grpcx_proto_reddb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcx_proto_reddb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_grpcx_proto_reddb_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryRequest) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *QueryRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *QueryRequest) GetParams() []*QueryValue {
	if x != nil {
		return x.Params
	}
	return nil
}

type QueryValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*QueryValue_NullValue
	//	*QueryValue_BoolValue
	//	*QueryValue_IntValue
	//	*QueryValue_FloatValue
	//	*QueryValue_TextValue
	//	*QueryValue_BytesValue
	//	*QueryValue_VectorValue
	//	*QueryValue_JsonValue
	//	*QueryValue_TimestampValue
	//	*QueryValue_UuidValue
	Kind          isQueryValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryValue) Reset() {
	*x = QueryValue{}
	mi := &file_grpcx_proto_reddb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryValue) ProtoMessage() {}

func (x *QueryValue) ProtoReflect() protoreflect.Message {
	mi := &file_grpcx_proto_reddb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryValue.ProtoReflect.Descriptor instead.
func (*QueryValue) Descriptor() ([]byte, []int) {
	return file_grpcx_proto_reddb_proto_rawDescGZIP(), []int{3}
}

func (x *QueryValue) GetKind() isQueryValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *QueryValue) GetNullValue() *QueryNull {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_NullValue); ok {
			return x.NullValue
		}
	}
	return nil
}

func (x *QueryValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *QueryValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *QueryValue) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *QueryValue) GetTextValue() string {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_TextValue); ok {
			return x.TextValue
		}
	}
	return ""
}

func (x *QueryValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *QueryValue) GetVectorValue() *QueryVector {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_VectorValue); ok {
			return x.VectorValue
		}
	}
	return nil
}

func (x *QueryValue) GetJsonValue() string {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_JsonValue); ok {
			return x.JsonValue
		}
	}
	return ""
}

func (x *QueryValue) GetTimestampValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return 0
}

func (x *QueryValue) GetUuidValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*QueryValue_UuidValue); ok {
			return x.UuidValue
		}
	}
	return nil
}

type isQueryValue_Kind interface {
	isQueryValue_Kind()
}

type QueryValue_NullValue struct {
	NullValue *QueryNull `protobuf:"bytes,1,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type QueryValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type QueryValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

type QueryValue_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,4,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type QueryValue_TextValue struct {
	TextValue string `protobuf:"bytes,5,opt,name=text_value,json=textValue,proto3,oneof"`
}

type QueryValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,6,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type QueryValue_VectorValue struct {
	VectorValue *QueryVector `protobuf:"bytes,7,opt,name=vector_value,json=vectorValue,proto3,oneof"`
}

type QueryValue_JsonValue struct {
	JsonValue string `protobuf:"bytes,8,opt,name=json_value,json=jsonValue,proto3,oneof"`
}

type QueryValue_TimestampValue struct {
	TimestampValue int64 `protobuf:"varint,9,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type QueryValue_UuidValue struct {
	UuidValue []byte `protobuf:"bytes,10,opt,name=uuid_value,json=uuidValue,proto3,oneof"`
}

func (*QueryValue_NullValue) isQueryValue_Kind() {}

func (*QueryValue_BoolValue) isQueryValue_Kind() {}

func (*QueryValue_IntValue) isQueryValue_Kind() {}

func (*QueryValue_FloatValue) isQueryValue_Kind() {}

func (*QueryValue_TextValue) isQueryValue_Kind() {}

func (*QueryValue_BytesValue) isQueryValue_Kind() {}

func (*QueryValue_VectorValue) isQueryValue_Kind() {}

func (*QueryValue_JsonValue) isQueryValue_Kind() {}

func (*QueryValue_TimestampValue) isQueryValue_Kind() {}

func (*QueryValue_UuidValue) isQueryValue_Kind() {}

type QueryNull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNull) Reset() {
	*x = QueryNull{}
	mi := &file_grpcx_proto_reddb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNull) ProtoMessage() {}

func (x *QueryNull) ProtoReflect() protoreflect.Message {
	mi := &file_grpcx_proto_reddb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNull.ProtoReflect.Descriptor instead.
func (*QueryNull) Descriptor() ([]byte, []int) {
	return file_grpcx_proto_reddb_proto_rawDescGZIP(), []int{4}
}

type QueryVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVector) Reset() {
	*x = QueryVector{}
	mi := &file_grpcx_proto_reddb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVector) ProtoMessage() {}

func (x *QueryVector) ProtoReflect() protoreflect.Message {
	mi := &file_grpcx_proto_reddb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVector.ProtoReflect.Descriptor instead.
func (*QueryVector) Descriptor() ([]byte, []int) {
	return file_grpcx_proto_reddb_proto_rawDescGZIP(), []int{5}
}

func (x *QueryVector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type QueryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Statement     string                 `protobuf:"bytes,3,opt,name=statement,proto3" json:"statement,omitempty"`
	Engine        string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"`
	Columns       []string               `protobuf:"bytes,5,rep,name=columns,proto3" json:"columns,omitempty"`
	RecordCount   uint64                 `protobuf:"varint,6,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	ResultJson    string                 `protobuf:"bytes,7,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryReply) Reset() {
	*x = QueryReply{}
	mi := &file_grpcx_proto_reddb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryReply) ProtoMessage() {}

func (x *QueryReply) ProtoReflect() protoreflect.Message {
	mi := &file_grpcx_proto_reddb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryReply.ProtoReflect.Descriptor instead.
func (*QueryReply) Descriptor() ([]byte, []int) {
	return file_grpcx_proto_reddb_proto_rawDescGZIP(), []int{6}
}

func (x *QueryReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *QueryReply) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *QueryReply) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *QueryReply) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *QueryReply) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *QueryReply) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *QueryReply) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

var File_grpcx_proto_reddb_proto protoreflect.FileDescriptor

const file_grpcx_proto_reddb_proto_rawDesc = "" +
	"\n" +
	"\x17grpcx/proto/reddb.proto\x12\breddb.v1\"\a\n" +
	"\x05Empty\"j\n" +
	"\vHealthReply\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12+\n" +
	"\x12checked_at_unix_ms\x18\x03 \x01(\x04R\x0fcheckedAtUnixMs\"\x99\x01\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12!\n" +
	"\fentity_types\x18\x02 \x03(\tR\ventityTypes\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12,\n" +
	"\x06params\x18\x04 \x03(\v2\x14.reddb.v1.QueryValueR\x06params\"\x9a\x03\n" +
	"\n" +
	"QueryValue\x124\n" +
	"\n" +
	"null_value\x18\x01 \x01(\v2\x13.reddb.v1.QueryNullH\x00R\tnullValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x04 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"text_value\x18\x05 \x01(\tH\x00R\ttextValue\x12!\n" +
	"\vbytes_value\x18\x06 \x01(\fH\x00R\n" +
	"bytesValue\x12:\n" +
	"\fvector_value\x18\a \x01(\v2\x15.reddb.v1.QueryVectorH\x00R\vvectorValue\x12\x1f\n" +
	"\n" +
	"json_value\x18\b \x01(\tH\x00R\tjsonValue\x12)\n" +
	"\x0ftimestamp_value\x18\t \x01(\x03H\x00R\x0etimestampValue\x12\x1f\n" +
	"\n" +
	"uuid_value\x18\n" +
	" \x01(\fH\x00R\tuuidValueB\x06\n" +
	"\x04kind\"\v\n" +
	"\tQueryNull\"%\n" +
	"\vQueryVector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\xc4\x01\n" +
	"\n" +
	"QueryReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1c\n" +
	"\tstatement\x18\x03 \x01(\tR\tstatement\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12\x18\n" +
	"\acolumns\x18\x05 \x03(\tR\acolumns\x12!\n" +
	"\frecord_count\x18\x06 \x01(\x04R\vrecordCount\x12\x1f\n" +
	"\vresult_json\x18\a \x01(\tR\n" +
	"resultJson2p\n" +
	"\x05RedDb\x120\n" +
	"\x06Health\x12\x0f.reddb.v1.Empty\x1a\x15.reddb.v1.HealthReply\x125\n" +
	"\x05Query\x12\x16.reddb.v1.QueryRequest\x1a\x14.reddb.v1.QueryReplyB0Z.github.com/reddb-io/reddb-go/grpcx/proto;protob\x06proto3"

var (
	file_grpcx_proto_reddb_proto_rawDescOnce sync.Once
	file_grpcx_proto_reddb_proto_rawDescData []byte
)

func file_grpcx_proto_reddb_proto_rawDescGZIP() []byte {
	file_grpcx_proto_reddb_proto_rawDescOnce.Do(func() {
		file_grpcx_proto_reddb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcx_proto_reddb_proto_rawDesc), len(file_grpcx_proto_reddb_proto_rawDesc)))
	})
	return file_grpcx_proto_reddb_proto_rawDescData
}

var file_grpcx_proto_reddb_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpcx_proto_reddb_proto_goTypes = []any{
	(*Empty)(nil),        // 0: reddb.v1.Empty
	(*HealthReply)(nil),  // 1: reddb.v1.HealthReply
	(*QueryRequest)(nil), // 2: reddb.v1.QueryRequest
	(*QueryValue)(nil),   // 3: reddb.v1.QueryValue
	(*QueryNull)(nil),    // 4: reddb.v1.QueryNull
	(*QueryVector)(nil),  // 5: reddb.v1.QueryVector
	(*QueryReply)(nil),   // 6: reddb.v1.QueryReply
}
var file_grpcx_proto_reddb_proto_depIdxs = []int32{
	3, // 0: reddb.v1.QueryRequest.params:type_name -> reddb.v1.QueryValue
	4, // 1: reddb.v1.QueryValue.null_value:type_name -> reddb.v1.QueryNull
	5, // 2: reddb.v1.QueryValue.vector_value:type_name -> reddb.v1.QueryVector
	0, // 3: reddb.v1.RedDb.Health:input_type -> reddb.v1.Empty
	2, // 4: reddb.v1.RedDb.Query:input_type -> reddb.v1.QueryRequest
	1, // 5: reddb.v1.RedDb.Health:output_type -> reddb.v1.HealthReply
	6, // 6: reddb.v1.RedDb.Query:output_type -> reddb.v1.QueryReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_grpcx_proto_reddb_proto_init() }
func file_grpcx_proto_reddb_proto_init() {
	if File_grpcx_proto_reddb_proto != nil {
		return
	}
	file_grpcx_proto_reddb_proto_msgTypes[3].OneofWrappers = []any{
		(*QueryValue_NullValue)(nil),
		(*QueryValue_BoolValue)(nil),
		(*QueryValue_IntValue)(nil),
		(*QueryValue_FloatValue)(nil),
		(*QueryValue_TextValue)(nil),
		(*QueryValue_BytesValue)(nil),
		(*QueryValue_VectorValue)(nil),
		(*QueryValue_JsonValue)(nil),
		(*QueryValue_TimestampValue)(nil),
		(*QueryValue_UuidValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcx_proto_reddb_proto_rawDesc), len(file_grpcx_proto_reddb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcx_proto_reddb_proto_goTypes,
		DependencyIndexes: file_grpcx_proto_reddb_proto_depIdxs,
		MessageInfos:      file_grpcx_proto_reddb_proto_msgTypes,
	}.Build()
	File_grpcx_proto_reddb_proto = out.File
	file_grpcx_proto_reddb_proto_goTypes = nil
	file_grpcx_proto_reddb_proto_depIdxs = nil
}
