// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: grpcx/proto/reddb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedDb_Health_FullMethodName = "/reddb.v1.RedDb/Health"
	RedDb_Query_FullMethodName  = "/reddb.v1.RedDb/Query"
)

// RedDbClient is the client API for RedDb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedDbClient interface {
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error)
}

type redDbClient struct {
	cc grpc.ClientConnInterface
}

func NewRedDbClient(cc grpc.ClientConnInterface) RedDbClient {
	return &redDbClient{cc}
}

func (c *redDbClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthReply)
	err := c.cc.Invoke(ctx, RedDb_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redDbClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryReply)
	err := c.cc.Invoke(ctx, RedDb_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedDbServer is the server API for RedDb service.
// All implementations must embed UnimplementedRedDbServer
// for forward compatibility.
type RedDbServer interface {
	Health(context.Context, *Empty) (*HealthReply, error)
	Query(context.Context, *QueryRequest) (*QueryReply, error)
	mustEmbedUnimplementedRedDbServer()
}

// UnimplementedRedDbServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedDbServer struct{}

func (UnimplementedRedDbServer) Health(context.Context, *Empty) (*HealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedRedDbServer) Query(context.Context, *QueryRequest) (*QueryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedRedDbServer) mustEmbedUnimplementedRedDbServer() {}
func (UnimplementedRedDbServer) testEmbeddedByValue()               {}

// UnsafeRedDbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedDbServer will
// result in compilation errors.
type UnsafeRedDbServer interface {
	mustEmbedUnimplementedRedDbServer()
}

func RegisterRedDbServer(s grpc.ServiceRegistrar, srv RedDbServer) {
	// If the following call pancis, it indicates UnimplementedRedDbServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedDb_ServiceDesc, srv)
}

func _RedDb_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedDbServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedDb_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedDbServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedDb_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedDbServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedDb_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedDbServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedDb_ServiceDesc is the grpc.ServiceDesc for RedDb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedDb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reddb.v1.RedDb",
	HandlerType: (*RedDbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _RedDb_Health_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _RedDb_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcx/proto/reddb.proto",
}
