#![allow(clippy::unwrap_used)]

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let routes_dir = manifest_dir.join("src/server/routes");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("route_discovery.rs");

    println!("cargo:rerun-if-changed={}", routes_dir.display());

    let mut route_files = Vec::new();
    collect_route_files(&routes_dir, &mut route_files);
    route_files.sort();

    let mut generated = String::new();
    generated.push_str("// @generated by crates/reddb-server/build.rs\n");
    generated.push_str(
        "// Files matching src/server/routes/**/*.route.rs are discovered automatically.\n\n",
    );

    for (index, path) in route_files.iter().enumerate() {
        generated.push_str(&format!(
            "#[path = {:?}]\nmod route_{index};\n",
            path.display().to_string()
        ));
    }

    generated.push_str(
        "\npub(crate) fn register_discovered_routes(registry: &mut crate::server::route_catalog::RouteRegistry) {\n",
    );
    for (index, path) in route_files.iter().enumerate() {
        let handler = route_handler_name(&routes_dir, path);
        generated.push_str(&format!(
            "    registry.with_handler(crate::server::RedDBServer::dispatch_{handler}_routes, route_{index}::register);\n"
        ));
    }
    generated.push_str("}\n");

    fs::write(out_file, generated).unwrap();
}

fn route_handler_name(routes_dir: &Path, path: &Path) -> String {
    let relative = path
        .strip_prefix(routes_dir)
        .expect("discovered route file is below routes directory");
    let mut parts: Vec<String> = relative
        .components()
        .map(|component| component.as_os_str().to_string_lossy().into_owned())
        .collect();
    let file = parts
        .pop()
        .expect("discovered route file has a file name")
        .trim_end_matches(".route.rs")
        .to_string();
    parts.push(file);
    parts.join("_").replace('-', "_")
}

fn collect_route_files(dir: &Path, route_files: &mut Vec<PathBuf>) {
    println!("cargo:rerun-if-changed={}", dir.display());

    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_route_files(&path, route_files);
        } else if path
            .file_name()
            .and_then(|name| name.to_str())
            .is_some_and(|name| name.ends_with(".route.rs"))
        {
            println!("cargo:rerun-if-changed={}", path.display());
            route_files.push(path);
        }
    }
}
