//! PG-Wire TLS end-to-end smoke (PRD #1621 slice 2, issue #1653).
//!
//! Drives the real `SSLRequest → 'S' → rustls handshake → full session`
//! path with a genuine tokio-rustls client against a self-signed dev cert
//! generated by the shared native-wire rcgen path. The listener's TLS
//! material is the same [`WireTlsConfig`] the RedWire transport uses — the
//! e2e proves the shared cert config negotiates and carries a query.
//!
//! It also pins the plaintext-vs-TLS posture matrix on a loopback bind:
//!   * TLS configured + `SSLRequest`  → `'S'`, handshake, full session.
//!   * TLS configured + plaintext startup (sslmode=disable) → still works
//!     on loopback (loopback trust permits plaintext).
//!   * No TLS configured + `SSLRequest` → `'N'`, client falls back to
//!     plaintext on the same socket.

use std::io::BufReader;
use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;

use reddb_server::wire::postgres::{start_pg_wire_listener, PgWireConfig};
use reddb_server::wire::tls::generate_self_signed_cert;
use reddb_server::wire::WireTlsConfig;
use reddb_server::{RedDBOptions, RedDBRuntime};
use tokio::io::{AsyncRead, AsyncReadExt, AsyncWrite, AsyncWriteExt};
use tokio::net::TcpStream;
use tokio::time::sleep;

const PG_SSL_REQUEST_CODE: u32 = 80_877_103;

struct TlsServer {
    addr: SocketAddr,
    cert_pem: String,
    _dir: tempfile::TempDir,
    _join: tokio::task::JoinHandle<()>,
}

/// Boot a PG-Wire listener with a freshly generated self-signed dev cert
/// written through the shared native-wire path. `with_tls = false` starts
/// the same listener without any TLS material so the `'N'` decline path
/// can be exercised.
async fn start_server(with_tls: bool) -> TlsServer {
    let probe = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
    let addr = probe.local_addr().unwrap();
    drop(probe);

    let dir = tempfile::tempdir().unwrap();
    let (cert_pem, key_pem) = generate_self_signed_cert("localhost").unwrap();
    let cert_path = dir.path().join("pg-tls-cert.pem");
    let key_path = dir.path().join("pg-tls-key.pem");
    std::fs::write(&cert_path, &cert_pem).unwrap();
    std::fs::write(&key_path, &key_pem).unwrap();

    let tls = with_tls.then(|| WireTlsConfig {
        cert_path,
        key_path,
    });

    let runtime = Arc::new(RedDBRuntime::with_options(RedDBOptions::in_memory()).unwrap());
    let cfg = PgWireConfig {
        bind_addr: addr.to_string(),
        tls,
        ..PgWireConfig::default()
    };
    let join = tokio::spawn(async move {
        let _ = start_pg_wire_listener(cfg, runtime).await;
    });
    // Listener binds inside the task; give it a tick before connecting.
    sleep(Duration::from_millis(50)).await;

    TlsServer {
        addr,
        cert_pem,
        _dir: dir,
        _join: join,
    }
}

/// Build a rustls client connector that trusts exactly the server's
/// self-signed cert, mirroring how a driver seeded with the dev cert
/// verifies `sslmode=require`.
fn client_connector(cert_pem: &str) -> tokio_rustls::TlsConnector {
    let _ = rustls::crypto::ring::default_provider().install_default();
    let mut roots = rustls::RootCertStore::empty();
    for cert in rustls_pemfile::certs(&mut BufReader::new(cert_pem.as_bytes())) {
        roots.add(cert.unwrap()).unwrap();
    }
    let config = rustls::ClientConfig::builder()
        .with_root_certificates(roots)
        .with_no_client_auth();
    tokio_rustls::TlsConnector::from(Arc::new(config))
}

/// Send an `SSLRequest` and return the single-byte server verdict.
async fn send_ssl_request<S>(stream: &mut S) -> u8
where
    S: AsyncRead + AsyncWrite + Unpin,
{
    stream.write_all(&8u32.to_be_bytes()).await.unwrap();
    stream
        .write_all(&PG_SSL_REQUEST_CODE.to_be_bytes())
        .await
        .unwrap();
    let mut verdict = [0u8; 1];
    stream.read_exact(&mut verdict).await.unwrap();
    verdict[0]
}

async fn write_startup<W: AsyncWrite + Unpin>(stream: &mut W) {
    let mut payload = Vec::new();
    payload.extend_from_slice(&((3u32) << 16).to_be_bytes());
    payload.extend_from_slice(b"user\0reddb\0");
    payload.push(0);
    let len = (payload.len() + 4) as u32;
    stream.write_all(&len.to_be_bytes()).await.unwrap();
    stream.write_all(&payload).await.unwrap();
}

async fn write_query<W: AsyncWrite + Unpin>(stream: &mut W, sql: &str) {
    let mut payload = Vec::new();
    payload.extend_from_slice(sql.as_bytes());
    payload.push(0);
    stream.write_all(&[b'Q']).await.unwrap();
    stream
        .write_all(&((payload.len() + 4) as u32).to_be_bytes())
        .await
        .unwrap();
    stream.write_all(&payload).await.unwrap();
}

async fn read_backend_frame<R: AsyncRead + Unpin>(stream: &mut R) -> (u8, Vec<u8>) {
    let mut tag = [0u8; 1];
    stream.read_exact(&mut tag).await.unwrap();
    let mut len = [0u8; 4];
    stream.read_exact(&mut len).await.unwrap();
    let len = u32::from_be_bytes(len) as usize;
    let mut body = vec![0u8; len - 4];
    stream.read_exact(&mut body).await.unwrap();
    (tag[0], body)
}

/// Read backend frames up to and including the terminating
/// ReadyForQuery ('Z').
async fn read_until_ready<R: AsyncRead + Unpin>(stream: &mut R) -> Vec<(u8, Vec<u8>)> {
    let mut frames = Vec::new();
    loop {
        let frame = read_backend_frame(stream).await;
        let done = frame.0 == b'Z';
        frames.push(frame);
        if done {
            return frames;
        }
    }
}

fn frame_tags(frames: &[(u8, Vec<u8>)]) -> Vec<char> {
    frames.iter().map(|(tag, _)| *tag as char).collect()
}

fn error_message(frames: &[(u8, Vec<u8>)]) -> Option<String> {
    let (_, body) = frames.iter().find(|(tag, _)| *tag == b'E')?;
    let mut pos = 0;
    while pos < body.len() {
        let field = body[pos];
        pos += 1;
        if field == 0 {
            break;
        }
        let end = body[pos..].iter().position(|&b| b == 0)? + pos;
        let value = std::str::from_utf8(&body[pos..end]).ok()?.to_string();
        pos = end + 1;
        if field == b'M' {
            return Some(value);
        }
    }
    None
}

fn command_tag(frames: &[(u8, Vec<u8>)]) -> Option<String> {
    let (_, body) = frames.iter().find(|(tag, _)| *tag == b'C')?;
    let nul = body.iter().position(|&b| b == 0).unwrap_or(body.len());
    Some(std::str::from_utf8(&body[..nul]).ok()?.to_string())
}

/// Run a CREATE/INSERT/SELECT round-trip over `stream` and assert the
/// SELECT streams the inserted rows back with no error frame. Proves a
/// full session survives whatever transport wraps `stream`.
async fn assert_full_session<S>(stream: &mut S)
where
    S: AsyncRead + AsyncWrite + Unpin,
{
    write_query(stream, "CREATE TABLE pg_tls_items (id INT)").await;
    let frames = read_until_ready(stream).await;
    assert!(
        error_message(&frames).is_none(),
        "CREATE failed: {:?}",
        error_message(&frames)
    );

    write_query(stream, "INSERT INTO pg_tls_items (id) VALUES (1), (2), (3)").await;
    let frames = read_until_ready(stream).await;
    assert!(
        error_message(&frames).is_none(),
        "INSERT failed: {:?}",
        error_message(&frames)
    );

    write_query(stream, "SELECT id FROM pg_tls_items").await;
    let frames = read_until_ready(stream).await;
    assert!(
        error_message(&frames).is_none(),
        "SELECT failed: {:?}",
        error_message(&frames)
    );
    let data_rows = frames.iter().filter(|(tag, _)| *tag == b'D').count();
    assert_eq!(
        data_rows,
        3,
        "SELECT should stream 3 rows over the transport, frames={:?}",
        frame_tags(&frames)
    );
    assert_eq!(command_tag(&frames).as_deref(), Some("SELECT 3"));
}

/// sslmode=require: SSLRequest → 'S' → rustls handshake → full session
/// over the encrypted stream, sharing the native cert config.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn sslmode_require_negotiates_tls_and_runs_full_session() {
    let server = start_server(true).await;
    let mut tcp = TcpStream::connect(server.addr).await.unwrap();

    let verdict = send_ssl_request(&mut tcp).await;
    assert_eq!(
        verdict, b'S',
        "TLS listener must accept SSLRequest with 'S'"
    );

    let connector = client_connector(&server.cert_pem);
    let server_name = rustls::pki_types::ServerName::try_from("localhost").unwrap();
    let mut tls = connector
        .connect(server_name, tcp)
        .await
        .expect("tls handshake");

    write_startup(&mut tls).await;
    let ready = read_until_ready(&mut tls).await;
    assert!(
        ready.iter().any(|(tag, _)| *tag == b'Z'),
        "startup should reach ReadyForQuery over TLS, frames={:?}",
        frame_tags(&ready)
    );

    assert_full_session(&mut tls).await;
}

/// TLS configured, but the client speaks plaintext (sslmode=disable):
/// on a loopback bind, loopback trust still admits the plaintext session.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn plaintext_still_works_on_loopback_when_tls_configured() {
    let server = start_server(true).await;
    let mut tcp = TcpStream::connect(server.addr).await.unwrap();

    // No SSLRequest — go straight to the plaintext startup flow.
    write_startup(&mut tcp).await;
    let ready = read_until_ready(&mut tcp).await;
    assert!(
        ready.iter().any(|(tag, _)| *tag == b'Z'),
        "loopback plaintext startup should reach ReadyForQuery, frames={:?}",
        frame_tags(&ready)
    );

    assert_full_session(&mut tcp).await;
}

/// No TLS material configured: SSLRequest is declined with 'N' and the
/// client continues plaintext on the same socket.
#[tokio::test(flavor = "multi_thread", worker_threads = 4)]
async fn ssl_request_declined_when_no_tls_configured() {
    let server = start_server(false).await;
    let mut tcp = TcpStream::connect(server.addr).await.unwrap();

    let verdict = send_ssl_request(&mut tcp).await;
    assert_eq!(
        verdict, b'N',
        "listener without TLS must decline SSLRequest with 'N'"
    );

    // Same socket: the client now sends a normal Startup and the session
    // proceeds in plaintext.
    write_startup(&mut tcp).await;
    let ready = read_until_ready(&mut tcp).await;
    assert!(
        ready.iter().any(|(tag, _)| *tag == b'Z'),
        "plaintext startup after 'N' should reach ReadyForQuery, frames={:?}",
        frame_tags(&ready)
    );
    assert_full_session(&mut tcp).await;
}
