from typing import Any

class KvClient:
    collection: str
    def __init__(self, transport: Any, collection: str = "kv_default") -> None: ...
    def watch(self, key: str, **opts: Any): ...
    def watch_prefix(self, prefix: str, **opts: Any): ...
    async def put(self, key: str, value: Any, **opts: Any) -> dict[str, Any]: ...
    async def invalidate_tags(self, tags: list[str], **opts: Any) -> int: ...

class Reddb:
    kv: KvClient
    def __init__(self, transport: Any) -> None: ...
    async def __aenter__(self) -> Reddb: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    async def query(
        self,
        sql: str,
        params: list[Any] | tuple[Any, ...] | None = None,
    ) -> dict[str, Any]: ...
    async def execute(
        self,
        sql: str,
        params: list[Any] | tuple[Any, ...] | None = None,
    ) -> dict[str, Any]: ...
    async def insert(self, collection: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def bulk_insert(self, collection: str, payloads: list[dict[str, Any]]) -> dict[str, Any]: ...
    async def get(self, collection: str, doc_id: str) -> dict[str, Any]: ...
    async def delete(self, collection: str, doc_id: str) -> dict[str, Any]: ...
    async def ping(self) -> dict[str, Any]: ...
    async def close(self) -> None: ...
    @property
    def transport(self) -> Any: ...

async def connect(uri: str, **opts: Any) -> Reddb: ...
