from typing import Any, Awaitable, Callable

from .documents import DocumentClient
from .kv import KvClient
from .queue import QueueClient

class Reddb:
    kv: KvClient
    documents: DocumentClient
    queue: QueueClient
    def __init__(self, transport: Any) -> None: ...
    async def __aenter__(self) -> Reddb: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    async def query(
        self,
        sql: str,
        params: list[Any] | tuple[Any, ...] | None = None,
    ) -> dict[str, Any]: ...
    async def execute(
        self,
        sql: str,
        params: list[Any] | tuple[Any, ...] | None = None,
    ) -> dict[str, Any]: ...
    async def insert(self, collection: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def bulk_insert(self, collection: str, payloads: list[dict[str, Any]]) -> dict[str, Any]: ...
    async def exists(self, collection: str, rid: Any) -> dict[str, bool]: ...
    async def transaction(self, callback: Callable[[Reddb], Awaitable[Any]]) -> Any: ...
    async def get(self, collection: str, doc_id: str) -> dict[str, Any]: ...
    async def delete(self, collection: str, doc_id: str) -> dict[str, Any]: ...
    async def ping(self) -> dict[str, Any]: ...
    async def close(self) -> None: ...
    @property
    def transport(self) -> Any: ...

async def connect(uri: str, **opts: Any) -> Reddb: ...
