from typing import Any

import httpx

DEFAULT_TIMEOUT_SECS: float

class HttpClient:
    def __init__(
        self,
        *,
        base_url: str,
        token: str | None = None,
        timeout: float = DEFAULT_TIMEOUT_SECS,
        verify: bool | str = True,
        client: httpx.AsyncClient | None = None,
    ) -> None: ...
    @property
    def token(self) -> str | None: ...
    def set_token(self, token: str | None) -> None: ...
    async def close(self) -> None: ...
    async def login(self, username: str, password: str) -> dict[str, Any]: ...
    async def query(
        self,
        sql: str,
        params: list[Any] | tuple[Any, ...] | None = None,
    ) -> dict[str, Any]: ...
    async def execute(
        self,
        sql: str,
        params: list[Any] | tuple[Any, ...] | None = None,
    ) -> dict[str, Any]: ...
    async def insert(self, collection: str, payload: dict[str, Any]) -> dict[str, Any]: ...
    async def bulk_insert(self, collection: str, payloads: list[dict[str, Any]]) -> dict[str, Any]: ...
    async def get(self, collection: str, doc_id: str) -> dict[str, Any]: ...
    async def delete(self, collection: str, doc_id: str) -> dict[str, Any]: ...
    def kv_watch(self, key: str, *, collection: str = "kv_default", since_lsn: int | None = None, limit: int | None = None): ...
    def kv_watch_prefix(self, prefix: str, *, collection: str = "kv_default", since_lsn: int | None = None, limit: int | None = None): ...
    async def scan(self, collection: str, **params: Any) -> dict[str, Any]: ...
    async def ping(self) -> dict[str, Any]: ...
    async def health(self) -> dict[str, Any]: ...
