from __future__ import annotations

import datetime as _datetime
import uuid as _uuid
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple, Union, overload

Scalar = Union[None, bool, int, float, str, bytes]
JsonValue = Union[None, bool, int, float, str, List["JsonValue"], Dict[str, "JsonValue"]]
VectorValue = Sequence[Union[int, float]]
ParamValue = Union[
    None,
    bool,
    int,
    float,
    str,
    bytes,
    bytearray,
    _datetime.datetime,
    _uuid.UUID,
    VectorValue,
    Mapping[str, JsonValue],
]
QueryResult = Dict[str, Any]
InsertResult = Dict[str, Any]
BulkInsertResult = Dict[str, Any]
DeleteResult = Dict[str, int]
ExistsResult = Dict[str, bool]
ListResult = Dict[str, Any]
CachePresence = str


class RedDbError(Exception):
    code: str
    message: str
    def __init__(self, code: str, message: str) -> None: ...


class CacheClient:
    def get(self, namespace: str, key: str) -> Optional[bytes]: ...
    def put(
        self,
        namespace: str,
        key: str,
        value: bytes,
        *,
        ttl_ms: Optional[int] = ...,
        tags: Optional[Sequence[str]] = ...,
    ) -> None: ...
    def exists(self, namespace: str, key: str) -> CachePresence: ...
    def invalidate(self, namespace: str, key: str) -> int: ...
    def invalidate_prefix(self, namespace: str, prefix: str) -> int: ...
    def invalidate_tags(self, namespace: str, tags: Sequence[str]) -> int: ...
    def flush_namespace(self, namespace: str) -> None: ...


class DocumentClient:
    def insert(self, collection: str, document: Mapping[str, JsonValue]) -> InsertResult: ...
    def get(self, collection: str, rid: str) -> Dict[str, Any]: ...
    def list(
        self,
        collection: str,
        *,
        limit: Optional[int] = ...,
        filter: Optional[str] = ...,
        order_by: Optional[str] = ...,
    ) -> ListResult: ...
    def patch(self, collection: str, rid: str, patch: Mapping[str, JsonValue]) -> Dict[str, Any]: ...
    def delete(self, collection: str, rid: str) -> DeleteResult: ...


class KvClient:
    def set(self, collection: str, key: str, value: JsonValue) -> QueryResult: ...
    def get(self, collection: str, key: str) -> Optional[JsonValue]: ...
    def exists(self, collection: str, key: str) -> ExistsResult: ...
    def delete(self, collection: str, key: str) -> DeleteResult: ...
    def list(
        self,
        collection: str,
        *,
        prefix: Optional[str] = ...,
        limit: Optional[int] = ...,
    ) -> ListResult: ...


class QueueClient:
    def create(self, name: str) -> QueryResult: ...
    def push(self, name: str, payload: JsonValue) -> QueryResult: ...
    def peek(self, name: str, limit: Optional[int] = ...) -> ListResult: ...
    def pop(self, name: str, limit: Optional[int] = ...) -> ListResult: ...
    def len(self, name: str) -> int: ...
    def purge(self, name: str) -> DeleteResult: ...
    def read_wait(
        self,
        name: str,
        consumer: str,
        wait_ms: int,
        *,
        group: Optional[str] = ...,
        count: Optional[int] = ...,
    ) -> ListResult: ...


TxBody = Any  # Callable[[TxClient], Any]


class TxClient:
    def begin(self) -> QueryResult: ...
    def commit(self) -> QueryResult: ...
    def rollback(self) -> QueryResult: ...
    def run(self, callback: TxBody) -> Any: ...


class RedDb:
    @overload
    def query(self, sql: str) -> QueryResult: ...
    @overload
    def query(self, sql: str, *args: ParamValue) -> QueryResult: ...
    @overload
    def query(self, sql: str, *, params: Optional[Sequence[ParamValue]]) -> QueryResult: ...
    @overload
    def execute(self, sql: str) -> QueryResult: ...
    @overload
    def execute(self, sql: str, *args: ParamValue) -> QueryResult: ...
    @overload
    def execute(self, sql: str, *, params: Optional[Sequence[ParamValue]]) -> QueryResult: ...
    def insert(self, collection: str, payload: Mapping[str, Scalar]) -> InsertResult: ...
    def bulk_insert(self, collection: str, payloads: Sequence[Mapping[str, Scalar]]) -> BulkInsertResult: ...
    def get(self, collection: str, rid: str) -> Optional[Dict[str, Any]]: ...
    def exists(self, collection: str, rid: str) -> ExistsResult: ...
    def list(
        self,
        collection: str,
        *,
        limit: Optional[int] = ...,
        filter: Optional[str] = ...,
        order_by: Optional[str] = ...,
    ) -> ListResult: ...
    def delete(self, collection: str, rid: str) -> DeleteResult: ...
    def health(self) -> Dict[str, Any]: ...
    def version(self) -> Dict[str, str]: ...
    @property
    def cache(self) -> CacheClient: ...
    @property
    def documents(self) -> DocumentClient: ...
    @property
    def kv(self) -> KvClient: ...
    @property
    def queues(self) -> QueueClient: ...
    @property
    def queue(self) -> QueueClient: ...
    @property
    def tx(self) -> TxClient: ...
    @property
    def helper_spec_version(self) -> str: ...
    def close(self) -> None: ...
    def __enter__(self) -> RedDb: ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...


class Connection:
    def query(self, sql: str) -> str: ...
    def execute(self, sql: str) -> Tuple[str, int]: ...
    def bulk_insert(self, collection: str, payloads: Sequence[str]) -> int: ...
    def create_row(self, collection: str, payload_json: str) -> int: ...
    def batch_query(self, queries: Sequence[str]) -> List[str]: ...
    def close(self) -> None: ...


class WireConnection:
    def query(self, sql: str) -> str: ...
    def query_raw(self, sql: str) -> int: ...
    def query_binary_raw(self, sql: str) -> int: ...
    def bulk_insert(self, collection: str, payloads: Sequence[str]) -> int: ...
    def bulk_insert_binary(self, collection: str, columns: Sequence[str], rows: Sequence[Sequence[Any]]) -> int: ...
    def close(self) -> None: ...


helper_spec_version: str

def connect(uri: str) -> RedDb: ...
def legacy_grpc_connect(addr: str) -> Connection: ...
def wire_connect(addr: str) -> WireConnection: ...
def wire_connect_tls(addr: str, ca_pem: str) -> WireConnection: ...
