{{- if .Values.ingress.enabled -}}
{{- $primarySvc := include "reddb.primary.fullname" . -}}
{{- $replicaSvc := include "reddb.replica.fullname" . -}}
{{- $primaryPort := .Values.primary.service.httpPort -}}
{{- $replicaPort := .Values.replica.service.httpPort -}}
{{- $mode := .Values.mode -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "reddb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- $svcName := $primarySvc -}}
          {{- $svcPort := $primaryPort -}}
          {{- if and (eq .backend "replica") (eq $mode "primary-replica") }}
          {{- $svcName = $replicaSvc -}}
          {{- $svcPort = $replicaPort -}}
          {{- end }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
