{{- if .Values.networkPolicy.enabled -}}
{{- if ne .Values.mode "cluster" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reddb.primary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  podSelector:
    matchLabels:
      {{- include "reddb.primary.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 5050
          protocol: TCP
        - port: 55055
          protocol: TCP
        - port: 5000
          protocol: TCP
      {{- if or (and (eq .Values.mode "primary-replica") (gt (int .Values.replica.replicaCount) 0)) .Values.networkPolicy.ingressFrom }}
      from:
        {{- if and (eq .Values.mode "primary-replica") (gt (int .Values.replica.replicaCount) 0) }}
        - podSelector:
            matchLabels:
              {{- include "reddb.replica.selectorLabels" . | nindent 14 }}
        {{- end }}
        {{- with .Values.networkPolicy.ingressFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
{{- if and (eq .Values.mode "primary-replica") (gt (int .Values.replica.replicaCount) 0) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reddb.replica.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
spec:
  podSelector:
    matchLabels:
      {{- include "reddb.replica.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 5050
          protocol: TCP
        - port: 55055
          protocol: TCP
        - port: 5000
          protocol: TCP
      {{- with .Values.networkPolicy.ingressFrom }}
      from:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- if eq .Values.mode "cluster" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reddb.cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster
spec:
  podSelector:
    matchLabels:
      {{- include "reddb.cluster.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: 5050
          protocol: TCP
        - port: 55055
          protocol: TCP
        - port: 5000
          protocol: TCP
      from:
        - podSelector:
            matchLabels:
              {{- include "reddb.cluster.selectorLabels" . | nindent 14 }}
        {{- with .Values.networkPolicy.ingressFrom }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
{{- end }}
