{{- if and .Values.pdb.enabled (eq .Values.mode "primary-replica") -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "reddb.replica.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
spec:
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "reddb.replica.selectorLabels" . | nindent 6 }}
{{- end }}
