{{- include "reddb.validateMode" . -}}
{{- if ne .Values.mode "cluster" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reddb.primary.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
  {{- with .Values.primary.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.primary.service.type }}
  ports:
    - name: wire
      port: {{ .Values.primary.service.wirePort }}
      targetPort: wire
      protocol: TCP
      appProtocol: tcp
      {{- if and (eq .Values.primary.service.type "NodePort") (.Values.primary.service.wireNodePort) }}
      nodePort: {{ .Values.primary.service.wireNodePort }}
      {{- end }}
    - name: grpc
      port: {{ .Values.primary.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
      {{- if and (eq .Values.primary.service.type "NodePort") (.Values.primary.service.grpcNodePort) }}
      nodePort: {{ .Values.primary.service.grpcNodePort }}
      {{- end }}
    {{- if .Values.grpc.tls.enabled }}
    - name: grpc-tls
      port: {{ .Values.primary.service.grpcTlsPort }}
      targetPort: grpc-tls
      protocol: TCP
      appProtocol: grpc
      {{- if and (eq .Values.primary.service.type "NodePort") (.Values.primary.service.grpcTlsNodePort) }}
      nodePort: {{ .Values.primary.service.grpcTlsNodePort }}
      {{- end }}
    {{- end }}
    - name: http
      port: {{ .Values.primary.service.httpPort }}
      targetPort: http
      protocol: TCP
      appProtocol: http
      {{- if and (eq .Values.primary.service.type "NodePort") (.Values.primary.service.httpNodePort) }}
      nodePort: {{ .Values.primary.service.httpNodePort }}
      {{- end }}
    {{- if .Values.http.tls.enabled }}
    - name: https
      port: {{ .Values.primary.service.httpTlsPort }}
      targetPort: https
      protocol: TCP
      appProtocol: https
      {{- if and (eq .Values.primary.service.type "NodePort") (.Values.primary.service.httpTlsNodePort) }}
      nodePort: {{ .Values.primary.service.httpTlsNodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "reddb.primary.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reddb.primary.headless" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: wire
      port: {{ .Values.primary.service.wirePort }}
      targetPort: wire
      protocol: TCP
    - name: grpc
      port: {{ .Values.primary.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    {{- if .Values.grpc.tls.enabled }}
    - name: grpc-tls
      port: {{ .Values.primary.service.grpcTlsPort }}
      targetPort: grpc-tls
      protocol: TCP
    {{- end }}
    - name: http
      port: {{ .Values.primary.service.httpPort }}
      targetPort: http
      protocol: TCP
    {{- if .Values.http.tls.enabled }}
    - name: https
      port: {{ .Values.primary.service.httpTlsPort }}
      targetPort: https
      protocol: TCP
    {{- end }}
  selector:
    {{- include "reddb.primary.selectorLabels" . | nindent 4 }}
{{- end }}
