{{- if and (eq .Values.mode "primary-replica") (gt (int .Values.replica.replicaCount) 0) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reddb.replica.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
  {{- with .Values.replica.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.replica.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.replica.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      appProtocol: grpc
    {{- if .Values.grpc.tls.enabled }}
    - name: grpc-tls
      port: {{ .Values.replica.service.grpcTlsPort }}
      targetPort: grpc-tls
      protocol: TCP
      appProtocol: grpc
    {{- end }}
    - name: http
      port: {{ .Values.replica.service.httpPort }}
      targetPort: http
      protocol: TCP
      appProtocol: http
    {{- if .Values.http.tls.enabled }}
    - name: https
      port: {{ .Values.replica.service.httpTlsPort }}
      targetPort: https
      protocol: TCP
      appProtocol: https
    {{- end }}
  selector:
    {{- include "reddb.replica.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reddb.replica.headless" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
    app.kubernetes.io/component: replica
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
    {{- if .Values.grpc.tls.enabled }}
    - name: grpc-tls
      port: 50052
      targetPort: grpc-tls
      protocol: TCP
    {{- end }}
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    {{- if .Values.http.tls.enabled }}
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
    {{- end }}
  selector:
    {{- include "reddb.replica.selectorLabels" . | nindent 4 }}
{{- end }}
