{{- $needAuthSecret := and .Values.auth.enabled (not .Values.auth.existingSecret) -}}
{{- $needCertSecret := and .Values.auth.vault.enabled .Values.auth.vault.certificate.value (not .Values.auth.vault.certificate.existingSecret) -}}
{{- if or $needAuthSecret $needCertSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reddb.authSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reddb.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $needAuthSecret }}
  username: {{ required "auth.username is required when auth.enabled=true" .Values.auth.username | quote }}
  password: {{ required "auth.password is required when auth.enabled=true and auth.existingSecret is empty" .Values.auth.password | quote }}
  {{- end }}
  {{- if $needCertSecret }}
  {{ .Values.auth.vault.certificate.existingSecretKey | default "certificate" }}: {{ .Values.auth.vault.certificate.value | quote }}
  {{- end }}
{{- end }}
